# Generated by Django 5.1 on 2024-08-30 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_folder_updated_at_alter_file_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='folder',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
